us-east-1version: 2
jobs:
  dockerbuild:
    machine: true
    steps:
      - checkout
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --region us-east-1 --no-include-email)
      - run:
          name: Build and push Docker image
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            docker build -t 492266378106.dkr.ecr.us-east-1.amazonaws.com/chat-demo:latest .
            docker push 492266378106.dkr.ecr.us-east-1.amazonaws.com/chat-demo:$TAG
  deployecs:
    machine: true
    steps:
      - run:
          name: install aws & ecs-deploy
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            sudo wget "https://raw.githubusercontent.com/silinternational/ecs-deploy/develop/ecs-deploy" -O /usr/local/bin/ecs-deploy
            sudo chmod +x /usr/local/bin/ecs-deploy
      - run:
          name: deploying to ECS
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            echo "ecs-deploy --region us-east-1 --cluster trambo --service-name trambo-TramboService-1OUCQ9V1XX8V2-Service-SULao5Ei8fYd --image 492266378106.dkr.ecr.us-east-1.amazonaws.com/chat-demo:latest --timeout 1800"
            ecs-deploy --region us-east-1 --cluster trambo --service-name trambo-TramboService-1OUCQ9V1XX8V2-Service-SULao5Ei8fYd --image 492266378106.dkr.ecr.us-east-1.amazonaws.com/chat-demo:latest --timeout 1800

workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: master
      - deployecs:
          requires:
            - dockerbuild
          filters:
            branches:
              only: master
